### ISSUE TITLE
Resource Quotas is null

### ISSUE THREAD

**Issue by chowyu08** [mlamina/Kubernetes-Manager#1]
# I have executed kubectl create -f k8s-manager , the kubernetes-manager dashboard bring up ,but the "Resource Quotas" is null,why?

**Comment by mlamina** [comment]
Does your Kubernetes cluster contain any resource quotas? 
You can find the documentation for quotas here: http://kubernetes.io/docs/admin/resourcequota/ http://kubernetes.io/docs/admin/resourcequota/

**Comment by chowyu08** [comment]
ok , I know, thanks!
I used to undestand that is pod 's resource.

2016-06-24 16:07 GMT+08:00 Marco Lamina notifications@github.com:

> Does your Kubernetes cluster contain any resource quotas?
> You can find the documentation for quotas here:
> http://kubernetes.io/docs/admin/resourcequota/ <
> http://kubernetes.io/docs/admin/resourcequota/>
>

**Comment by mlamina** [comment]
Glad I could help! Can I mark this issue as resolved?

**Comment by chowyu08** [comment]
#

**Comment by chowyu08** [comment]
yes

2016-06-28 0:42 GMT+08:00 Marco Lamina notifications@github.com:

> Glad I could help! Can I mark this issue as resolved?
>
