### ISSUE TITLE
node-detail.js file is wrong.

### ISSUE THREAD

**Issue by main1015** [mlamina/Kubernetes-Manager#2]
My English is not good, I hope the following description you can understand.
I through docker container is not the Kubernetes-Manager but I found when access nodes interface and inside the control chart cannot be displayed in a browser that is' ReferenceError: value is not defined, corresponding to this is' /api/v1/proxy/namespaces/ kube-system/services/k8s-manager/components/nodes/node-detail.js:26:20 'file error, I look at the source code that you to parameter name wrong in judging percentage. Now I don't know how container docker on this side of the change, so the trouble you

**Comment by mlamina** [comment]
Thank you for submitting the bug! I fixed it and I'll soon update the docker image.

**Comment by main1015** [comment]
Polite
