### ISSUE TITLE
k8s-Manager Update problems

### ISSUE THREAD

**Issue by xiaosadexiaohai** [mlamina/Kubernetes-Manager#3]
I really like this UI and is currently has abandoned the project, pay close attention to for a long time, has been waiting for the new version of the update! ~!

**Comment by xiaosadexiaohai** [comment]
@mlamina

**Comment by mlamina** [comment]
Sorry, I haven't had the time to keep working on the project. You're more than welcome to contribute, of course :) 

Also, maybe check out the official [Kubernetes dashboard](https://github.com/kubernetes/dashboard). It has come a long way and is actively developed!
